import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Header from '../components/header'

const inter = Inter({ subsets: ['latin'] })
interface RootLayoutProps {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}:RootLayoutProps) {
  return (
    <html lang="en"style={{height: '100%'}}>
      <body className={inter.className} style={{height: '100%'}}>
        {/* <Header /> */}
        {children}
        </body>
    </html>
  )
}
